run_name: Qwen_iter10
output_dir: Qwen_iter10
model_name_or_path: Qwen_iter9
ref_model: Qwen_iter9
learning_rate: 5.0e-7
num_train_epochs: 2
logging_steps: 2
gradient_checkpointing: true
do_train: true
do_eval: true
eval_steps: 10000
choose_type: max_min
train_dir: ./iter_dpo_rule_reward/Test10_Qwen_iter10_reward.json
eval_dir: ./iter_dpo_rule_reward/Test10_Qwen_iter10_reward.json
loss_type: sigmoid
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1000
eval_strategy: steps
bf16: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 16
report_to: wandb
label_smoothing: 0.1
eot_token: <|im_end|>
